# Node.js Function App to Linux on Azure
# Build a Node.js function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr: none

stages:
 - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: dev-nl-dbw-agent-pool
        workspace:
          clean: all

        steps:
          - checkout: self
            persistCredentials: true
          - task: UseNode@1
            inputs:
              version: '20.x'
            displayName: 'Install Node.js'